package edu.pte.mik.model;

import junit.framework.TestCase;

import static org.junit.Assert.assertTrue;

public class PasswordTest extends TestCase {

    // Test data was generated by https://www.md5hashgenerator.com/

    public void testToHex1() {
        byte[] data = Password.getHash("MyTestPassword");
        String h1 = Password.toHex1(data);
        assertEquals("72418435a5ebb5949ccaa42f55bc15f3", h1);
    }

    public void testToHex2() {
        byte[] data = Password.getHash("MyTestPassword");
        String h2 = Password.toHex2(data);
        assertEquals("72418435a5ebb5949ccaa42f55bc15f3", h2);
    }

    public void testToHex3() {
        byte[] data = Password.getHash("MyTestPassword");
        String h3 = Password.toHex3(data);
        assertEquals("72418435a5ebb5949ccaa42f55bc15f3", h3);
    }

    public void testEqualsTo() {
        Password pwd1 = Password.createFromPassword("MyTestPassword");
        Password pwd2 = Password.createFromPassword("MyTestPassword");
        Password pwd3 = Password.createFromPassword("MyWrongTestPassword");
        Password pwd4 = Password.createFromHash("72418435a5ebb5949ccaa42f55bc15f3");
        Password pwd5 = Password.createFromHash("72418435a5ebb5949ccaa42f55bc15f2");

        assertTrue(pwd1.equalsTo(pwd2));
        assertFalse(pwd1.equalsTo(pwd3));
        assertTrue(pwd1.equalsTo(pwd4));
        assertFalse(pwd1.equalsTo(pwd5));
    }
}