package edu.pte.mik.prog2;

public abstract class Vehicle {

    /*
    Almost all components were generated by Idea upon request of developer
     */

    private static int baseRentalFee;

    public static int getBaseRentalFee() {
        return baseRentalFee;
    }

    public static void setBaseRentalFee(int baseRentalFee) {
        Vehicle.baseRentalFee = baseRentalFee;
    }

    private String license;
    private String make;

    public String getLicense() {
        return license;
    }

    public String getMake() {
        return make;
    }

    public Vehicle(String license, String make) {
        this.license = license;
        this.make = make;
    }

    public Integer getRentalPrice(Integer days) {
        // static member can be accessed from instance method
        return baseRentalFee * days;
    }
}
