package edu.pte.mik.prog2;

public class Car extends Vehicle {
    /*
    Almost all components were generated by Idea upon request of developer
     */

    private static int baseRentalFee;
    private static int comfortFee;

    public static int getBaseRentalFee() {
        return baseRentalFee;
    }

    public static void setBaseRentalFee(int baseRentalFee) {
        Car.baseRentalFee = baseRentalFee;
    }

    public static int getComfortFee() {
        return comfortFee;
    }

    public static void setComfortFee(int comfortFee) {
        Car.comfortFee = comfortFee;
    }

    private Integer comfortLevel;

    public Integer getComfortLevel() {
        return comfortLevel;
    }

    public void setComfortLevel(Integer comfortLevel) {
        this.comfortLevel = comfortLevel;
    }

    public Car(String license, String make, Integer comfortLevel) {
        super(license, make);
        this.comfortLevel = comfortLevel;
    }

    public Integer getRentalPrice(Integer days) {
        // static member can be accessed from instance method
        // rental price of ancestor is also used
        // To identify local, instance or static members, check their colors
        return super.getRentalPrice(days) + (baseRentalFee + comfortFee * comfortLevel) * days;
    }

    @Override
    public String toString() {
        return "edu.pte.mik.prog2.Car{" +
                "license='" + getLicense() + '\'' +
                ", make='" + getMake() + '\'' +
                ", comfortLevel=" + comfortLevel +
                ", daily rental price=" + getRentalPrice(1) +
                '}';
    }
}
